services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      WP_HOST: ${WP_HOST}
      WP_SITEURL: ${WP_SITEURL}
    networks:
      - webnet
    volumes:
      - wordpress_data:/var/www/html
  mariadb:
    build: ./requirements/mariadb
    container_name: ${MYSQL_HOST}
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - webnet
    volumes:
      - mariadb_data:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
    - 443:443
    networks:
      - webnet
    volumes:
      - wordpress_data:/var/www/html

networks:
  webnet:

volumes:
  mariadb_data:
  wordpress_data: