volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${INTRA}/data/volumes/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${INTRA}/data/volumes/wordpress
      o: bind

services:
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_pass
      - wp_admin_pass
      - wp_user_pass
    networks:
      - webnet
    volumes:
      - wordpress_data:/var/www/html
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - webnet
    volumes:
      - mariadb_data:/var/lib/mariadb
    secrets:
      - db_pass
      - db_root_pass
  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - webnet
    volumes:
      - wordpress_data:/var/www/html
  redis:
    build: ./bonus/redis
    image: redis:inception
    container_name: redis
    networks:
      - webnet
    restart: unless-stopped
    environment:
      REDIS_PORT: ${REDIS_PORT}
  proftpd:
    build: ./bonus/proftpd
    image: proftpd:inception
    container_name: proftpd
    depends_on:
      - wordpress
    networks:
      - webnet
    restart: unless-stopped
    ports:
      - 21:21
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - INTRA=${INTRA}
    secrets:
      - ftp_pass

networks:
  webnet:


secrets:
  db_root_pass:
    file: ../secrets/db_root_pass
  db_pass:
    file: ../secrets/db_pass
  wp_user_pass:
    file: ../secrets/wp_user_pass
  wp_admin_pass:
    file: ../secrets/wp_admin_pass
  ftp_pass:
    file: ../secrets/ftp_pass
