volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${INTRA}/data/volumes/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${INTRA}/data/volumes/wordpress
      o: bind

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_HOST: ${WP_HOST}
      WP_SITEURL: ${WP_SITEURL}
      INTRA: ${INTRA}
    networks:
      - webnet
    volumes:
      - wordpress_data:/var/www/html
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - webnet
    volumes:
      - mariadb_data:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
    - 443:443
    networks:
      - webnet
    volumes:
      - wordpress_data:/var/www/html

networks:
  webnet:
